version: 1.2
service:
   subclass: NOT_APPLICABLE
   name: Big Service Files
   author: Walt Shands
   description: |
      This service uses very big files
   files:
      - verylargewdl.wdl
      - verylargewdl2.wdl
      - verylargewdl.wdl.morethan5MB
